networks:
  default:
    name: ${NW_NAME?}_nw
    ipam:
      config:
        - subnet: 172.28.38.0/24

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: app
    hostname: app
    volumes:
      - .:/app
    ports:
      - "127.0.0.1:8080:80"
    networks:
      - default
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      XDEBUG_MODE: ${XDEBUG_MODE:-off}
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG:-serverName=app}